### ISSUE TITLE
Query doesn't work for the numbers enclosed within single quotes

### ISSUE THREAD

**Issue by guruvi** [nearform/sql#23]
```const SQL = require("@nearform/sql");```

```
const query1 = SQL`
            SELECT
              uuid,
              schedule_time
            FROM
              job
            WHERE 
              schedule_time 
                BETWEEN 
              current_date + integer '29'
                AND 
              current_date + integer '30'`;
      const response = await fastify.pg.query(query1);
```
The above query works, whereas the below one didn't work.

```
const n = 29;
const query2 = SQL`
            SELECT
              uuid,
              schedule_time
            FROM
              job
            WHERE 
              schedule_time 
                BETWEEN 
              current_date + integer ${n}
                AND 
              current_date + integer ${n+1}`;
      const response = await fastify.pg.query(query2);
```

Seems to be some issue with NearForm sql. I have to make it work with normal string.

**Comment by p16** [comment]
Hi @guruvi ,
what is the SQL error you get when executing the second query?

**Comment by guruvi** [comment]
Thanks @p16!

It is a Postgres error because of malformed query

```
 { error: invalid input syntax for integer: "$1"
        at Connection.Object.<anonymous>.Connection.parseE (/Users/gursivas/Documents/Falabella/Workspace/scheduler-service/node_modules/pg/lib/connection.js:602:11)
        at Connection.Object.<anonymous>.Connection.parseMessage (/Users/gursivas/Documents/Falabella/Workspace/scheduler-service/node_modules/pg/lib/connection.js:399:19)
        at Socket.<anonymous> (/Users/gursivas/Documents/Falabella/Workspace/scheduler-service/node_modules/pg/lib/connection.js:121:22)
        at Socket.emit (events.js:189:13)
        at addChunk (_stream_readable.js:284:12)
        at readableAddChunk (_stream_readable.js:265:11)
        at Socket.Readable.push (_stream_readable.js:220:10)
        at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
      name: 'error',
      length: 95,
      severity: 'ERROR',
      code: '22P02',
      detail: undefined,
      hint: undefined,
      position: '90',
      internalPosition: undefined,
      internalQuery: undefined,
      where: undefined,
      schema: undefined,
      table: undefined,
      column: undefined,
      dataType: undefined,
      constraint: undefined,
      file: 'numutils.c',
      line: '62',
      routine: 'pg_atoi' }
```

**Comment by p16** [comment]
@guruvi from the error you posted it seems you can't use `integer` because the statement is a prepared one (it has placeholders instead of the actual values, they will be replaced by postgres when executing the query).

You should try using something like `CAST(${n} AS INTEGER)` or `${n}::integer`.

Or even simpler: does it work if you just remove `integer`? I think it should

**Comment by p16** [comment]
marking as a question and closing.

**Comment by guruvi** [comment]
Thanks @p16 ! That helped.
